package Projeto::Model::DBICSchemamodel;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Projeto::DBSchema',
    
    
);

=head1 NAME

Projeto::Model::DBICSchemamodel - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Projeto>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Projeto::DBSchema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.4

=head1 AUTHOR

Daniel Ruoso

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
